platform :ios, '8.0'
target "GraduationProject-ZCC" do
pod 'SVProgressHUD'
pod 'SDWebImage'
pod 'AFNetworking'
pod 'MJRefresh'
pod 'UMengAnalytics'
pod 'BaiduMapKit'
pod 'BmobSDK'
pod 'UMengUShare/Social/Sina'
pod 'UMengUShare/Social/QQ'
pod 'UMengUShare/Social/WeChat'
pod 'UMengUShare/UI'
pod 'pop'
pod 'Hyphenate'

end
